---
- name: to be installed
  debug: var=packages

- name: update cache
  sudo: true
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: ensure packages exist
  sudo: true
  apt: pkg={{item}} state=latest
  with_items: packages
